## numpy 기초

### 라이브러리 호출

In [1]:
# numpy 라이브러리를 호출합니다.
import numpy as np

### 1차원 배열 생성

In [2]:
# 리스트로 1차원 배열을 생성합니다.
ar1 = np.array(object = [1, 2, 3])

In [3]:
# ar1을 출력합니다. 원소를 가로 방향으로 출력합니다.
ar1

array([1, 2, 3])

In [4]:
# ar1의 클래스를 확인합니다. ar1의 클래스는 numpy.ndarray입니다.
type(ar1)

numpy.ndarray

In [5]:
# ar1의 형태(행 개수, 열 개수)를 확인합니다.
ar1.shape

(3,)

In [6]:
# ar1의 원소 개수를 확인합니다.
ar1.size

3

In [7]:
# ar1의 원소 자료형을 확인합니다. ar1의 원소 자료형은 numpy.int64입니다.
# [참고] Windows에서는 정수를 numpy.int32로 생성합니다.
ar1.dtype

dtype('int64')

### 1차원 배열의 원소 자료형 변환

In [8]:
# 다양한 자료형을 원소로 갖는 리스트를 생성합니다.
a = [1, 2.0, '3']

In [9]:
# 리스트로 배열을 생성하면 원소 자료형을 자동 변환합니다.
# [참고] 정수 < 실수 < 문자열 방향으로 변환합니다.
ar1 = np.array(object = a)

In [10]:
# ar1을 출력합니다. ar1의 원소 자료형은 '<U32'입니다.
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [11]:
# ar1의 원소 자료형을 실수로 변환합니다.
ar1.astype(float)

array([1., 2., 3.])

In [12]:
# ar1의 원소 자료형을 실수로 변환하면 여전히 배열이므로 이어서 정수로 변환할 수 있습니다.
ar1.astype(float).astype(int)

array([1, 2, 3])

### [참고] 배열을 생성할 때 원소 자료형 지정

In [13]:
# 배열의 원소 자료형을 실수로 지정합니다.
np.array(object = a, dtype = float)

array([1., 2., 3.])

In [14]:
# 배열의 원소 자료형을 정수로 지정합니다.
np.array(object = a, dtype = int)

array([1, 2, 3])

In [15]:
# 배열의 원소 자료형을 문자열로 지정합니다.
np.array(object = a, dtype = str)

array(['1', '2.0', '3'], dtype='<U3')

In [16]:
# 배열의 원소 자료형을 객체로 지정합니다.
# 리스트의 원소 자료형을 그대로 유지합니다.
np.array(object = a, dtype = object)

array([1, 2.0, '3'], dtype=object)

### 간격이 일정한 배열 생성

In [17]:
# 0부터 4까지 연속된 정수를 반환합니다.
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
# 1부터 5까지 연속된 정수를 반환합니다.
np.arange(start = 1, stop = 6)

array([1, 2, 3, 4, 5])

In [19]:
# 1부터 10에서 홀수인 정수를 반환합니다.
np.arange(start = 1, stop = 11, step = 2)

array([1, 3, 5, 7, 9])

In [20]:
# 0부터 1까지 0.1 간격의 연속된 실수를 반환합니다. [참고] 1을 포함하지 않습니다.
np.arange(start = 0, stop = 1, step = 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [21]:
# 0~1을 10등분하는 (즉, 원소가 11개인) 실수형 배열을 생성합니다.
np.linspace(start = 0, stop = 1, num = 10+1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [22]:
# 80~75를 30등분하는 실수형 배열을 생성합니다.
np.linspace(start = 80, stop = 75, num = 30+1)

array([80.        , 79.83333333, 79.66666667, 79.5       , 79.33333333,
       79.16666667, 79.        , 78.83333333, 78.66666667, 78.5       ,
       78.33333333, 78.16666667, 78.        , 77.83333333, 77.66666667,
       77.5       , 77.33333333, 77.16666667, 77.        , 76.83333333,
       76.66666667, 76.5       , 76.33333333, 76.16666667, 76.        ,
       75.83333333, 75.66666667, 75.5       , 75.33333333, 75.16666667,
       75.        ])

### 원소를 반복한 배열 생성

In [23]:
# 배열의 전체 원소를 두 번 반복합니다.
np.tile(A = ar1, reps = 2)

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [24]:
# 배열의 각 원소를 두 번씩 반복합니다.
np.repeat(a = ar1, repeats = 2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [25]:
# 배열 원소별로 반복할 횟수를 지정합니다.
np.repeat(a = ar1, repeats = [3, 2, 1])

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

In [26]:
# 반복 횟수를 range() 함수로 지정할 수 있습니다.
np.repeat(a = ar1, repeats = range(3, 0, -1))

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

### 1차원 배열 인덱싱 및 슬라이싱

In [27]:
# 1부터 11까지 홀수인 정수를 원소로 갖는 1차원 배열을 생성합니다. 
ar1 = np.arange(start = 1, stop = 12, step = 2)

In [28]:
# ar1의 0번 인덱스(첫 번째) 원소를 선택합니다.
ar1[0]

1

In [29]:
# ar1의 1번 인덱스(두 번째) 원소를 선택합니다.
ar1[1]

3

In [30]:
# ar1의 -1번 인덱스(마지막) 원소를 선택합니다.
ar1[-1]

11

In [31]:
# ar1의 0~2번 인덱스 원소를 선택합니다. 
ar1[:3]

array([1, 3, 5])

In [32]:
# ar1의 3번 인덱스 원소부터 마지막 원소까지 선택합니다.
ar1[3:]

array([ 7,  9, 11])

In [33]:
# 정수 스칼라 또는 슬라이스 대신 리스트를 지정하는 배열 인덱싱이 가능합니다.
# [주의] 리스트는 배열 인덱싱을 실행할 수 없습니다!
ar1[[3, 2, 1]]

array([7, 5, 3])

In [34]:
# 리스트 원소를 반복하면 같은 원소를 여러 번 선택합니다.
ar1[[3, 3, 3]]

array([7, 7, 7])

### 2차원 배열 생성

In [35]:
# 같은 길이의 리스트를 원소로 갖는 리스트로 2차원 배열을 생성합니다.
ar2 = np.array(object = [[1, 2, 3], [4, 5, 6]])

In [36]:
# ar2를 출력합니다. 전체 원소를 2행 3열로 배치합니다.
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# ar2의 클래스를 확인합니다. ar2의 클래스는 numpy.ndarray입니다.
type(ar2)

numpy.ndarray

In [38]:
# ar2의 형태(행 개수, 열 개수)를 확인합니다.
ar2.shape

(2, 3)

In [39]:
# ar2의 원소 개수를 확인합니다.
ar2.size

6

In [40]:
# ar2의 원소 자료형을 확인합니다. ar2의 원소 자료형은 numpy.int64입니다.
ar2.dtype

dtype('int64')

### 배열의 재구조화

In [41]:
# 0부터 11까지 12개의 정수를 원소로 갖는 1차원 배열을 생성합니다.
ar1 = np.arange(12)

In [42]:
# ar1을 4행 3열인 2차원 배열로 변환합니다. 원소 입력 방향은 가로입니다.
# [주의] 1차원 배열 원소 개수의 약수만 행 또는 열 개수로 설정할 수 있습니다.
ar1.reshape(4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
# order = 'F'를 추가하면 원소 입력 방향을 세로로 변경합니다.
# [참고] order 매개변수에 전달하는 인수의 기본값은 'C'입니다.
ar1.reshape(4, 3, order = 'F')

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [44]:
# ar1을 4행 3열인 2차원 배열로 변환하고 ar2에 할당합니다.
# [참고] 열 위치에 -1을 지정하면 열 개수를 자동 계산합니다.
ar2 = ar1.reshape(4, -1)
ar2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
# 2차원 배열을 1차원 배열로 변환합니다.
ar2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### [참고] 배열의 결합

In [46]:
# 원소 개수가 같은 1차원 배열을 가로 방향으로 쌓은 2차원 배열을 생성합니다.
np.column_stack(tup = (ar1, ar1))

array([[ 0,  0],
       [ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 4,  4],
       [ 5,  5],
       [ 6,  6],
       [ 7,  7],
       [ 8,  8],
       [ 9,  9],
       [10, 10],
       [11, 11]])

In [47]:
# 원소 개수가 같은 1차원 배열을 세로 방향으로 쌓은 2차원 배열을 생성합니다.
np.row_stack(tup = (ar1, ar1))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [48]:
# 두 개 이상의 1차원 배열을 일렬로 결합하여 커다란 1차원 배열을 생성합니다.
# [참고] 리스트를 + 연산자로 결합하는 것과 같은 동작입니다.
np.concatenate((ar1, ar1))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11])

### 2차원 배열 인덱싱 및 슬라이싱

In [49]:
# ar2의 1행 1열 원소를 선택합니다.
ar2[0, 0]

0

In [50]:
# ar2의 2행 2열 원소를 선택합니다. 
ar2[1, 1]

4

In [51]:
# ar2의 1~2행 1~2열 원소를 선택합니다.
ar2[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [52]:
# ar2의 전체 행 2~3열 원소를 선택합니다.
# [주의] 전체 행을 선택하려면 빈 콜론을 추가합니다.
ar2[:, 1:3]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [53]:
# ar2의 일부 열 순서를 변경합니다.
# [주의] 행과 열 순서를 함께 변경할 수 없습니다.
ar2[:, [2, 1]]

array([[ 2,  1],
       [ 5,  4],
       [ 8,  7],
       [11, 10]])

### 배열 산술 연산

In [54]:
# 원소가 3개인 1차원 배열을 생성합니다.
ar1 = np.array(object = range(3))
ar1

array([0, 1, 2])

In [55]:
# 3행 1열인 2차원 배열을 생성합니다.
ar2 = ar1.reshape(-1, 1)
ar2

array([[0],
       [1],
       [2]])

In [56]:
# ar1의 각 원소에 1을 더합니다.
ar1 + 1

array([1, 2, 3])

In [57]:
# ar2의 각 원소에 2를 곱합니다.
ar2 * 2

array([[0],
       [2],
       [4]])

In [58]:
# ar1과 ar2를 더합니다.
ar1 + ar2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### 수학 관련 값과 함수

In [59]:
# 자연상수(2.7182)를 반환합니다.
np.e

2.718281828459045

In [60]:
# 파이(3.141592)를 반환합니다.
np.pi

3.141592653589793

In [61]:
# 결측값을 반환합니다.
np.nan

nan

In [62]:
# 무한대를 반환합니다.
np.inf

inf

In [63]:
# 소수점을 버립니다.
np.floor(np.e)

2.0

In [64]:
# 소수점을 올립니다.
np.ceil(np.pi)

4.0

In [65]:
# 소수점 둘째자리까지 남도록 반올림합니다.
np.round(np.e, 2)

2.72

In [66]:
# 제곱근을 반환합니다.
np.sqrt(4)

2.0

In [67]:
# 거듭제곱을 반환합니다.
np.power(2, 3)

8

In [68]:
# 자연상수 거듭제곱을 반환합니다.
np.exp(1)

2.718281828459045

In [69]:
# 자연로그를 반환합니다.
np.log(10)

2.302585092994046

In [70]:
# 모든 원소를 더합니다.
np.sum(ar1)

3

In [71]:
# 모든 원소를 곱합니다.
np.prod(ar1)

0

In [72]:
# 원소의 차이를 반환합니다.
np.diff(ar1)

array([1, 1])

In [73]:
# 최솟값을 반환합니다.
np.min(ar1)

0

In [74]:
# 최댓값을 반환합니다.
np.max(ar1)

2

In [75]:
# 평균을 반환합니다.
np.mean(ar1)

1.0

In [76]:
# 중위수를 반환합니다.
np.median(ar1)

1.0

In [77]:
# 분산을 반환합니다.
np.var(ar1)

0.6666666666666666

In [78]:
# 표준편차를 반환합니다.
np.std(ar1)

0.816496580927726

In [79]:
# 원소 개수를 반환합니다.
np.size(ar1)

3

## End of Document