## Day 2

In [1]:
s = {3, 1, 2, 1}
s

{1, 2, 3}

In [2]:
type(s)

set

In [3]:
b = [1, 5, 3]
b

[1, 5, 3]

In [10]:
b = set(b)

In [5]:
list(s)

[1, 2, 3]

In [6]:
s & b

{1, 3}

In [7]:
s | b

{1, 2, 3, 5}

In [9]:
s - b

{2}

In [18]:
# 리스트 생성
a = [1, 1.0, '1', '2', 2.0, 2]
b = ['2', 2, 2.0, 3.0, 3, '3']

In [19]:
# 집합이 되면서 정수와 실수는 하나로 합쳐지는데 앞선 자료형으로 통일됨
sa = set(a)
sa

{1, '1', '2', 2.0}

In [20]:
# 자료형의 순서는 정수, 문자열, 실수 순
sb = set(b)
sb

{2, '2', '3', 3.0}

In [21]:
# 교집합은 뒤에 오는 집합의 자료형으로 통일됨
sa & sb

{2, '2'}

In [22]:
# 합집합은 앞에 오는 집합의 자료형으로 통일됨
sa | sb

{1, '1', '2', 2.0, '3', 3.0}

### 신민철님 질문

In [34]:
# 리스트 생성
a = [1, 1.0, '1', '2', 2.0, 2]
b = ['2', 2, 2.0, 3.0, 3, '3']

# 집합이 되면서 정수와 실수는 하나로 합쳐지는데 앞선 자료형으로 통일됨
sa = set(a)
print('sa는', sa)

# 자료형의 순서는 정수, 문자열, 실수 순
sb = set(b)
print('sb는', sb)

# 교집합은 뒤에 오는 집합의 자료형으로 통일됨
print('교집합은', sa & sb)

# 합집합은 앞에 오는 집합의 자료형으로 통일됨
print('합집합은', sa | sb)

sa는 {'2', 1, 2.0, '1'}
sb는 {'2', 2, 3.0, '3'}
교집합은 {'2', 2}
합집합은 {1, 2.0, 3.0, '3', '2', '1'}


In [ ]:
'교집합'

In [1]:
%whos

Interactive namespace is empty.


In [2]:
major = input('전공: ')

전공: 응용통계학


In [3]:
%whos

Variable   Type    Data/Info
----------------------------
major      str     응용통계학


In [4]:
print(major)

응용통계학


In [7]:
major = input('전공: ')
if '통계' in major:
    print('Study R!')
elif '컴퓨터' in major:
    print('Study Python!')
else:
    print('Study anything!')

전공: 경제학
Study anything!


In [8]:
menu = ['짜장면', '탕수육', '짬뽕', '깐풍기', '전가복', '샥스핀']

In [11]:
for item in menu:
    print(item)

짜장면
탕수육
짬뽕
깐풍기
전가복
샥스핀


In [15]:
for item in menu:
    print(item, '시킬까요?')

짜장면 시킬까요?
탕수육 시킬까요?
짬뽕 시킬까요?
깐풍기 시킬까요?
전가복 시킬까요?
샥스핀 시킬까요?


In [17]:
for item in menu:
    print(item, '시킬까요?')
    if item in ['짜장면', '짬뽕']:
        print('-> 요리부터 주문합시다!')
    print('-> 다음 메뉴가 뭔가요?\n')

짜장면 시킬까요?
-> 요리부터 주문합시다!
-> 다음 메뉴가 뭔가요?

탕수육 시킬까요?
-> 다음 메뉴가 뭔가요?

짬뽕 시킬까요?
-> 요리부터 주문합시다!
-> 다음 메뉴가 뭔가요?

깐풍기 시킬까요?
-> 다음 메뉴가 뭔가요?

전가복 시킬까요?
-> 다음 메뉴가 뭔가요?

샥스핀 시킬까요?
-> 다음 메뉴가 뭔가요?



In [18]:
for item in menu:
    print(item, '시킬까요?')
    if item in ['짜장면', '짬뽕']:
        continue
        print('-> 요리부터 주문합시다!')
    print('-> 다음 메뉴가 뭔가요?\n')

짜장면 시킬까요?
탕수육 시킬까요?
-> 다음 메뉴가 뭔가요?

짬뽕 시킬까요?
깐풍기 시킬까요?
-> 다음 메뉴가 뭔가요?

전가복 시킬까요?
-> 다음 메뉴가 뭔가요?

샥스핀 시킬까요?
-> 다음 메뉴가 뭔가요?



In [19]:
for item in menu:
    print(item, '시킬까요?')
    if item in ['전가복', '샥스핀']:
        break
        print('-> 요리부터 주문합시다!')
    print('-> 다음 메뉴가 뭔가요?\n')

짜장면 시킬까요?
-> 다음 메뉴가 뭔가요?

탕수육 시킬까요?
-> 다음 메뉴가 뭔가요?

짬뽕 시킬까요?
-> 다음 메뉴가 뭔가요?

깐풍기 시킬까요?
-> 다음 메뉴가 뭔가요?

전가복 시킬까요?


### 김한수님 질문

In [20]:
name = ['hansoo', 'hoon']
rate = [1.0, 1.3]

In [21]:
for i, y in zip(name, rate):
    print(f"{i} pay low cost tax {y:.2f}%")

hansoo pay low cost tax 1.00%
hoon pay low cost tax 1.30%


### 명지우님 질문

In [25]:
# ctrl + /: 주석 일괄 처리
for i in range(2, 20):
    print(f'*** {i}단 ***')
    for j in range(1, 20):
        print(f'{i} * {j} = {i*j}')
    print('')

*** 2단 ***
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
2 * 11 = 22
2 * 12 = 24
2 * 13 = 26
2 * 14 = 28
2 * 15 = 30
2 * 16 = 32
2 * 17 = 34
2 * 18 = 36
2 * 19 = 38

*** 3단 ***
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30
3 * 11 = 33
3 * 12 = 36
3 * 13 = 39
3 * 14 = 42
3 * 15 = 45
3 * 16 = 48
3 * 17 = 51
3 * 18 = 54
3 * 19 = 57

*** 4단 ***
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40
4 * 11 = 44
4 * 12 = 48
4 * 13 = 52
4 * 14 = 56
4 * 15 = 60
4 * 16 = 64
4 * 17 = 68
4 * 18 = 72
4 * 19 = 76

*** 5단 ***
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50
5 * 11 = 55
5 * 12 = 60
5 * 13 = 65
5 * 14 = 70
5 * 15 = 75
5 * 16 = 80
5 * 17 = 85
5 * 18 = 90
5 * 19 = 95

*** 6단 ***
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42

In [30]:
for i, j in zip(range(1, 20), range(1, 10)):
    print(f'{i} * {j} = {i*j}')

1 * 1 = 1
2 * 2 = 4
3 * 3 = 9
4 * 4 = 16
5 * 5 = 25
6 * 6 = 36
7 * 7 = 49
8 * 8 = 64
9 * 9 = 81


In [35]:
nums = list(range(1, 11))
nums

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [39]:
sqrs = []

In [40]:
%whos

Variable   Type     Data/Info
-----------------------------
a          list     n=6
b          list     n=6
i          int      9
item       str      전가복
j          int      9
major      str      경제학
menu       list     n=6
name       list     n=2
num        int      1
nums       list     n=10
rate       list     n=2
sa         set      {'2', 1, 2.0, '1'}
sb         set      {'2', 2, 3.0, '3'}
sqrs       list     n=0
y          float    1.3


In [41]:
for num in nums:
    sqrs.append(num ** 2)

In [42]:
sqrs

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [45]:
[num ** 2 for num in nums]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [46]:
sqrs = []
for num in nums:
    if num % 2 == 0:
        sqrs.append(num ** 2)
sqrs

[4, 16, 36, 64, 100]

In [47]:
[num ** 2 for num in nums if num % 2 == 0]

[4, 16, 36, 64, 100]

In [ ]:
for i in range(2, 20):
    for j in range(1, 20):
        print(f'{i} * {j} = {i*j}')

In [48]:
[f'{i} * {j} = {i*j}' for i in range(2, 20) for j in range(1, 20)]

['2 * 1 = 2',
 '2 * 2 = 4',
 '2 * 3 = 6',
 '2 * 4 = 8',
 '2 * 5 = 10',
 '2 * 6 = 12',
 '2 * 7 = 14',
 '2 * 8 = 16',
 '2 * 9 = 18',
 '2 * 10 = 20',
 '2 * 11 = 22',
 '2 * 12 = 24',
 '2 * 13 = 26',
 '2 * 14 = 28',
 '2 * 15 = 30',
 '2 * 16 = 32',
 '2 * 17 = 34',
 '2 * 18 = 36',
 '2 * 19 = 38',
 '3 * 1 = 3',
 '3 * 2 = 6',
 '3 * 3 = 9',
 '3 * 4 = 12',
 '3 * 5 = 15',
 '3 * 6 = 18',
 '3 * 7 = 21',
 '3 * 8 = 24',
 '3 * 9 = 27',
 '3 * 10 = 30',
 '3 * 11 = 33',
 '3 * 12 = 36',
 '3 * 13 = 39',
 '3 * 14 = 42',
 '3 * 15 = 45',
 '3 * 16 = 48',
 '3 * 17 = 51',
 '3 * 18 = 54',
 '3 * 19 = 57',
 '4 * 1 = 4',
 '4 * 2 = 8',
 '4 * 3 = 12',
 '4 * 4 = 16',
 '4 * 5 = 20',
 '4 * 6 = 24',
 '4 * 7 = 28',
 '4 * 8 = 32',
 '4 * 9 = 36',
 '4 * 10 = 40',
 '4 * 11 = 44',
 '4 * 12 = 48',
 '4 * 13 = 52',
 '4 * 14 = 56',
 '4 * 15 = 60',
 '4 * 16 = 64',
 '4 * 17 = 68',
 '4 * 18 = 72',
 '4 * 19 = 76',
 '5 * 1 = 5',
 '5 * 2 = 10',
 '5 * 3 = 15',
 '5 * 4 = 20',
 '5 * 5 = 25',
 '5 * 6 = 30',
 '5 * 7 = 35',
 '5 * 8 = 40',
 '5 *

In [50]:
for i in enumerate(nums):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
(7, 8)
(8, 9)
(9, 10)


In [51]:
for index, value in enumerate(nums):
    print(f'{index} 인덱스 원소의 값은 {value}입니다.')

0 인덱스 원소의 값은 1입니다.
1 인덱스 원소의 값은 2입니다.
2 인덱스 원소의 값은 3입니다.
3 인덱스 원소의 값은 4입니다.
4 인덱스 원소의 값은 5입니다.
5 인덱스 원소의 값은 6입니다.
6 인덱스 원소의 값은 7입니다.
7 인덱스 원소의 값은 8입니다.
8 인덱스 원소의 값은 9입니다.
9 인덱스 원소의 값은 10입니다.


In [53]:
nums[2] = '3'

In [54]:
for num in nums:
    print(num ** 2)

1
4


TypeError: unsupported operand type(s) for ** or pow(): 'str' and 'int'

In [55]:
for num in nums:
    try:
        print(num ** 2)
    except:
        print('에러가 발생했습니다!')

1
4
에러가 발생했습니다!
16
25
36
49
64
81
100


In [56]:
for num in nums:
    try:
        print(num ** 2)
    except Exception as e:
        print(e)

1
4
unsupported operand type(s) for ** or pow(): 'str' and 'int'
16
25
36
49
64
81
100


In [57]:
i = 5
while i > 0:
    print(i)
    i -= 1

5
4
3
2
1


In [58]:
def BMI(height, weight):
    bmi = weight / (height/100)**2
    return bmi

In [59]:
BMI(175, 65)

21.224489795918366

In [60]:
BMI(height = 175, weight = 65)

21.224489795918366

In [61]:
BMI(weight = 65, height = 175)

21.224489795918366

In [62]:
BMI(65, 175)

414.20118343195264

In [63]:
def BMI(height = 175, weight = 65):
    bmi = weight / (height/100)**2
    return bmi

In [64]:
BMI()

21.224489795918366

In [65]:
BMI(height = 190, weight = 95)

26.315789473684212

In [66]:
BMI2 = lambda height, weight: weight / (height/100)**2

In [67]:
BMI2(175, 65)

21.224489795918366

In [68]:
(lambda height, weight: weight / (height/100)**2)(175, 65)

21.224489795918366

In [69]:
def printValues1(a, b, c):
    for i in [a, b, c]:
        print(i)

In [70]:
printValues1(a = 1, b = 2, c = 3)

1
2
3


In [71]:
printValues1(a = 1, b = 2)

TypeError: printValues1() missing 1 required positional argument: 'c'

In [73]:
def printValues2(*args):
    for i in args:
        print(i)

In [74]:
printValues2(1, 2, 3)

1
2
3


In [75]:
printValues2(1, 2)

1
2


In [85]:
def printValues3(**kwargs):
    for i in kwargs.items():
        print(f'{i[0]}은(는) {i[1]}입니다.')

In [86]:
printValues3(메뉴 = '순대국', 가격 = 9000)

메뉴은(는) 순대국입니다.
가격은(는) 9000입니다.


In [87]:
import os, shutil

In [88]:
os.getcwd()

'/Users/drkevin/Documents/PythonBasicProgramming-main/code'

In [ ]:
# 절대경로 방식
os.chdir(path = '/Users/drkevin/Documents/PythonBasicProgramming-main/data')

In [89]:
# 상대경로 방식
os.chdir(path = '../data')

In [90]:
os.getcwd()

'/Users/drkevin/Documents/PythonBasicProgramming-main/data'

In [91]:
file = open(file = 'test.txt', mode = 'w', encoding = 'UTF-8')

In [92]:
for i in range(1, 6):
    file.write(f'{i}번째 페이지 수집 중!\n')

In [93]:
file.close()

In [94]:
file = open(file = 'test.txt', mode = 'a', encoding = 'UTF-8')

In [95]:
for i in range(11, 16):
    file.write(f'{i}번째 페이지 수집 중!\n')

In [96]:
file.close()

In [97]:
file = open(file = 'test.txt', mode = 'r', encoding = 'UTF-8')

In [98]:
text = file.read()

In [99]:
text

'1번째 페이지 수집 중!\n2번째 페이지 수집 중!\n3번째 페이지 수집 중!\n4번째 페이지 수집 중!\n5번째 페이지 수집 중!\n11번째 페이지 수집 중!\n12번째 페이지 수집 중!\n13번째 페이지 수집 중!\n14번째 페이지 수집 중!\n15번째 페이지 수집 중!\n'

In [100]:
type(text)

str

In [101]:
text.encode(encoding = 'UTF-8')

b'1\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n2\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n3\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n4\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n5\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n11\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n12\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n13\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n14\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n15\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xe

In [102]:
file = open(file = 'test.txt', mode = 'rb')

In [103]:
text = file.read()

In [104]:
text

b'1\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n2\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n3\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n4\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n5\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n11\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n12\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n13\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n14\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n15\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xe

In [105]:
type(text)

bytes

In [106]:
text.decode(encoding = 'UTF-8')

'1번째 페이지 수집 중!\n2번째 페이지 수집 중!\n3번째 페이지 수집 중!\n4번째 페이지 수집 중!\n5번째 페이지 수집 중!\n11번째 페이지 수집 중!\n12번째 페이지 수집 중!\n13번째 페이지 수집 중!\n14번째 페이지 수집 중!\n15번째 페이지 수집 중!\n'

### 김근환님 질문

In [110]:
file = open(file = 'test.txt', mode = 'rb')

In [111]:
text = file.read()

In [112]:
text

b'1\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n2\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n3\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n4\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n5\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n11\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n12\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n13\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n14\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n15\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xe

In [113]:
text

b'1\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n2\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n3\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n4\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n5\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n11\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n12\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n13\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n14\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xec\x88\x98\xec\xa7\x91 \xec\xa4\x91!\n15\xeb\xb2\x88\xec\xa7\xb8 \xed\x8e\x98\xec\x9d\xb4\xec\xa7\x80 \xe

In [114]:
os.mkdir(path = './temp')

In [115]:
shutil.copy(src = 'test.txt', dst = 'copy1.txt')

'copy1.txt'

In [116]:
shutil.copy(src = 'test.txt', dst = './temp')

'./temp/test.txt'

In [117]:
shutil.move(src = 'copy1.txt', dst = './temp')

'./temp/copy1.txt'

In [118]:
os.listdir()

['temp',
 'Naver_APT_Detail_Seoul.xlsx',
 'Naver_APT_Detail_Seoul.csv',
 'APT_Price_Seoul_2021.csv',
 'KBO_Hitters_2021.xlsx',
 'KBO_Hitters_2021.csv',
 'test.txt',
 'APT_Price_Seoul_2021.xlsx']

In [120]:
files = [i for i in os.listdir() if 'xlsx' in i]
files

['Naver_APT_Detail_Seoul.xlsx',
 'KBO_Hitters_2021.xlsx',
 'APT_Price_Seoul_2021.xlsx']

In [121]:
for file in files:
    shutil.copy(src = file, dst = './temp')

In [122]:
os.listdir(path = './temp')

['Naver_APT_Detail_Seoul.xlsx',
 'copy1.txt',
 'KBO_Hitters_2021.xlsx',
 'test.txt',
 'APT_Price_Seoul_2021.xlsx']

In [123]:
os.chdir(path = './temp')

In [124]:
os.getcwd()

'/Users/drkevin/Documents/PythonBasicProgramming-main/data/temp'

In [125]:
os.listdir()

['Naver_APT_Detail_Seoul.xlsx',
 'copy1.txt',
 'KBO_Hitters_2021.xlsx',
 'test.txt',
 'APT_Price_Seoul_2021.xlsx']

In [126]:
os.rename(src = 'test.txt', dst = 'copy2.txt')

In [127]:
os.mkdir(path = './temp2')

In [128]:
os.remove(path = 'copy1.txt')

In [129]:
os.remove(path = './temp2')

PermissionError: [Errno 1] Operation not permitted: './temp2'

In [130]:
for i in os.listdir():
    os.remove(i)

PermissionError: [Errno 1] Operation not permitted: 'temp2'

In [131]:
print(i)

temp2


In [132]:
os.path.isdir(i)

True

In [133]:
os.path.isfile(i)

False

In [134]:
for i in os.listdir():
    if os.path.isfile(i):
        os.remove(i)

In [ ]:
not os.path.isdir(s = i)

In [135]:
os.chdir('..')

In [136]:
os.getcwd()

'/Users/drkevin/Documents/PythonBasicProgramming-main/data'

In [137]:
os.listdir()

['temp',
 'Naver_APT_Detail_Seoul.xlsx',
 'Naver_APT_Detail_Seoul.csv',
 'APT_Price_Seoul_2021.csv',
 'KBO_Hitters_2021.xlsx',
 'KBO_Hitters_2021.csv',
 'test.txt',
 'APT_Price_Seoul_2021.xlsx']

In [138]:
os.rmdir('temp')

OSError: [Errno 66] Directory not empty: 'temp'

In [139]:
shutil.rmtree('temp')

In [140]:
from datetime import datetime, timedelta

In [141]:
ctime = datetime.now()

In [142]:
ctime

datetime.datetime(2022, 4, 26, 13, 43, 49, 803433)

In [143]:
ctime.date()

datetime.date(2022, 4, 26)

In [144]:
ctime.time()

datetime.time(13, 43, 49, 803433)

In [145]:
ctime.timestamp()

1650948229.803433

In [146]:
ctime.strftime('%Y년 %m월 %d일 %H:%M:%S %A')

'2022년 04월 26일 13:43:49 Tuesday'

In [147]:
birth = '2001년 2월 3일 4시 5분 6초'
birth = datetime.strptime(birth, '%Y년 %m월 %d일 %H시 %M분 %S초')
birth

datetime.datetime(2001, 2, 3, 4, 5, 6)

In [148]:
birth = datetime(2001, 2, 3, 4, 5, 6)
birth

datetime.datetime(2001, 2, 3, 4, 5, 6)

In [149]:
dtGap = ctime - birth

In [151]:
dtGap.days

7752

In [153]:
dtGap.days * 3 * 7000

162792000

In [154]:
dir(dtGap)

['__abs__',
 '__add__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__pos__',
 '__radd__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 'days',
 'max',
 'microseconds',
 'min',
 'resolution',
 'seconds',
 'total_seconds']

In [155]:
d_day = datetime(2022, 1, 1, 19, 0, 0)

In [156]:
d_day + timedelta(days = 99)

datetime.datetime(2022, 4, 10, 19, 0)

In [158]:
spot = d_day - timedelta(hours = 2)

In [160]:
spot.strftime('%m월 %d일')

'01월 01일'

In [166]:
ctime = datetime.now()
today = ctime.strftime('%y/%m/%d')

In [167]:
fileName = f'Result_{today}.xlsx'
fileName

'Result_22/04/26.xlsx'

In [168]:
import locale

In [169]:
locale.getlocale(category = locale.LC_TIME)

(None, None)

In [170]:
locale.setlocale(category = locale.LC_TIME, locale = 'ko_KR')

'ko_KR'

In [171]:
ctime.strftime('%Y년 %m월 %d일 %H:%M:%S %A')

'2022년 04월 26일 14:22:15 화요일'

In [172]:
import numpy as np

In [173]:
ar1 = np.array([1, 2, 3])

In [174]:
ar1

array([1, 2, 3])

In [175]:
print(ar1)

[1 2 3]


In [176]:
a = [1, 2, 3]

In [177]:
print(a)

[1, 2, 3]


In [178]:
type(ar1)

numpy.ndarray

In [179]:
type(a)

list

In [180]:
ar1.ndim

1

In [181]:
ar1.shape

(3,)

In [182]:
ar1.dtype

dtype('int64')

In [183]:
a = [1, 2.0, '3']

In [184]:
ar1 = np.array(a)

In [185]:
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [186]:
ar1.astype('float')

array([1., 2., 3.])

In [187]:
ar1.astype('int')

ValueError: invalid literal for int() with base 10: '2.0'

In [188]:
ar1.astype('float').astype('int')

array([1, 2, 3])

In [189]:
np.array(object = a, dtype = 'float')

array([1., 2., 3.])

In [190]:
np.array(object = a, dtype = 'int')

array([1, 2, 3])

In [191]:
np.array(object = a, dtype = 'str')

array(['1', '2.0', '3'], dtype='<U3')

In [192]:
np.array(object = a, dtype = 'object')

array([1, 2.0, '3'], dtype=object)

In [193]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [194]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [195]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [196]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [197]:
range(0, 1, 0.1)

TypeError: 'float' object cannot be interpreted as an integer

In [198]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [199]:
np.linspace(0, 1, num = 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [200]:
np.linspace(80, 75, num = 32)

array([80.        , 79.83870968, 79.67741935, 79.51612903, 79.35483871,
       79.19354839, 79.03225806, 78.87096774, 78.70967742, 78.5483871 ,
       78.38709677, 78.22580645, 78.06451613, 77.90322581, 77.74193548,
       77.58064516, 77.41935484, 77.25806452, 77.09677419, 76.93548387,
       76.77419355, 76.61290323, 76.4516129 , 76.29032258, 76.12903226,
       75.96774194, 75.80645161, 75.64516129, 75.48387097, 75.32258065,
       75.16129032, 75.        ])

In [201]:
ar1

array(['1', '2.0', '3'], dtype='<U32')

In [202]:
np.tile(ar1, 2)

array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

In [203]:
np.repeat(ar1, 2)

array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

In [204]:
np.repeat(ar1, [1, 2, 3])

array(['1', '2.0', '2.0', '3', '3', '3'], dtype='<U32')

In [206]:
np.repeat(ar1, range(3, 0, -1))

array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

In [207]:
ar1 = np.arange(1, 12, 2)
ar1

array([ 1,  3,  5,  7,  9, 11])

In [208]:
ar1[0]

1

In [209]:
type(ar1[0])

numpy.int64

In [210]:
ar1[1]

3

In [211]:
ar1[-1]

11

In [212]:
ar1[[3, 2, 1]]

array([7, 5, 3])

In [213]:
a

[1, 2.0, '3']

In [214]:
a[[2, 1, 0]]

TypeError: list indices must be integers or slices, not list

In [215]:
ar1[[3, 3, 3]]

array([7, 7, 7])

In [216]:
ar1[range(1, 4)]

array([3, 5, 7])

In [248]:
np.tile(np.array([3]), 100)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [218]:
ar1[np.tile(np.array([3]), 100)]

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [219]:
ar1[:3]

array([1, 3, 5])

In [220]:
ar1[3:]

array([ 7,  9, 11])

In [221]:
ar1[:]

array([ 1,  3,  5,  7,  9, 11])

In [222]:
ar2 = np.array([[1, 2, 3], [4, 5, 6]])

In [223]:
ar2

array([[1, 2, 3],
       [4, 5, 6]])

In [224]:
type(ar2)

numpy.ndarray

In [225]:
ar2.ndim

2

In [226]:
ar2.shape

(2, 3)

In [227]:
ar2.dtype

dtype('int64')

In [228]:
ar1 = np.arange(12)
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [229]:
ar1.reshape(3, 4, order = 'C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [230]:
ar1.reshape(3, 4, order = 'F')

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [231]:
ar2 = ar1.reshape(4, -1)
ar2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [232]:
ar2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [233]:
ar2 = ar1.reshape(3, 4, order = 'F')

In [235]:
ar2.flatten(order = 'F')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [237]:
ar2 = ar1.reshape(4, -1)
ar2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [238]:
ar2[0, 0]

0

In [239]:
ar2[1, 1]

4

In [240]:
ar2[0:2, 0:2]

array([[0, 1],
       [3, 4]])

In [241]:
ar2[:, 1:3]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [242]:
ar2[:, [2, 1]]

array([[ 2,  1],
       [ 5,  4],
       [ 8,  7],
       [11, 10]])

In [243]:
ar1 = np.array(range(3))
ar1

array([0, 1, 2])

In [244]:
ar2 = ar1.reshape(-1, 1)
ar2

array([[0],
       [1],
       [2]])

In [245]:
ar1 + 1

array([1, 2, 3])

In [246]:
ar2 * 2

array([[0],
       [2],
       [4]])

In [247]:
ar1 + ar2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [249]:
import pandas as pd

In [250]:
sr = pd.Series(data = np.arange(1, 6, 2))
sr

0    1
1    3
2    5
dtype: int64

In [251]:
type(sr)

pandas.core.series.Series

In [252]:
sr.ndim

1

In [253]:
sr.shape

(3,)

In [254]:
sr.dtypes

dtype('int64')

In [255]:
sr1 = pd.Series(data = [1, 2.0, '3'])
sr1

0      1
1    2.0
2      3
dtype: object

In [257]:
for i in range(3):
    print(type(sr1[i]))

<class 'int'>
<class 'float'>
<class 'str'>


In [259]:
pd.Series(data = {'a': 1, 'b': 3, 'c': 5})

a    1
b    3
c    5
dtype: int64

In [260]:
sr

0    1
1    3
2    5
dtype: int64

In [261]:
sr.values

array([1, 3, 5])

In [262]:
sr.index

RangeIndex(start=0, stop=3, step=1)

In [263]:
sr.index = ['a', 'b', 'c']

In [264]:
sr

a    1
b    3
c    5
dtype: int64

In [266]:
sr.iloc[0]

1

In [267]:
sr.iloc[[0]]

a    1
dtype: int64

In [268]:
sr.iloc[[0, 2]]

a    1
c    5
dtype: int64

In [269]:
sr.iloc[0:2]

a    1
b    3
dtype: int64

In [270]:
sr.loc['a']

1

In [271]:
sr.loc[['a']]

a    1
dtype: int64

In [272]:
sr.loc[['a', 'c']]

a    1
c    5
dtype: int64

In [273]:
sr.loc['a':'c']

a    1
b    3
c    5
dtype: int64

In [274]:
sr >= 3

a    False
b     True
c     True
dtype: bool

In [275]:
sr.loc[sr >= 3]

b    3
c    5
dtype: int64

In [276]:
sr.iloc[sr >= 3]

ValueError: iLocation based boolean indexing cannot use an indexable as a mask

In [277]:
sr[sr >= 3]

b    3
c    5
dtype: int64

In [279]:
sr >= 3

a    False
b     True
c     True
dtype: bool

In [284]:
sr < 5

a     True
b     True
c    False
dtype: bool

In [285]:
(sr >= 3) & (sr < 5)

a    False
b     True
c    False
dtype: bool

In [286]:
sr.loc[(sr >= 3) & (sr < 5)]

b    3
dtype: int64